services:
  - type: web
    name: omega-account-planner
    env: python
    plan: free
    region: oregon
    buildCommand: pip install -r requirements.txt
    startCommand: python app/app.py
    autoDeploy: true
